MANAG-6: draft of auth page
pyramidum-space/frontend pull request #3
Opened 2024-04-14 09:42 UTC by MaxibX

2024-04-21 13:38 UTC, sergomyaso requested changes, later dismissed

2024-04-21 13:38 UTC, sergomyaso commented on src/components/Auth.vue
> +        <h1>{{"Pyramidum"}}</h1>
Почему не просто `<h1>Pyramidum</h1>?`

2024-04-21 13:38 UTC, sergomyaso commented on src/components/Auth.vue
> +                {{"Забыли пароль?"}}
Можно просто текст, у тебя же динамики нет

2024-05-06 09:59 UTC, sergomyaso commented on src/components/Auth.vue
> +                    if (this.password == '') {
this.username_msg = this.username === '' ? 'Пожалуйста, введите логин' : '';
this.password_msg = this.password === '' ? 'Пожалуйста, введите пароль' : '';

if (this.username !== '' && this.password !== '') {
    // Запрос к БД. Переход к пользовательскому окну
}

2024-05-13 12:22 UTC, fatalistix approved these changes

2024-05-13 12:23 UTC, merged