Conte 12 add header and tasks components
pyramidum-space/frontend pull request #6
Opened 2024-04-14 14:26 UTC by DmitryStonie

Я не использовал vue. Вопрос: надо ли разбивать TaskBody на отдельные компоненты?

2024-04-21 13:45 UTC, sergomyaso requested changes

2024-04-21 13:45 UTC, sergomyaso commented on src/components/TaskBody.vue
> +          <option
`
const options = ['option1', 'option2']
{options.map((option) => (
                            <option key={option} value={option}>
                                {option}
                            </option>
                        ))}
                        `

2024-04-21 13:45 UTC, sergomyaso commented on src/components/TaskBody.vue
> +          <option
ну и везде ниже по коду

2024-04-21 13:45 UTC, sergomyaso commented on src/components/TaskBody.vue
> +          <option
Идея простая, ты в цикле ресуешь компоненты, проходясь по массиву options

2024-04-21 15:39 UTC, DmitryStonie commented on src/components/TaskBody.vue
> +          <option
Исправил

2024-05-02 15:08 UTC, sergomyaso approved these changes

2024-05-02 15:08 UTC, merged